kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: image-store
spec:
  template:
    metadata:
      labels:
        app: image-store-app
    spec:
      containers:
      - name: image-store
        image: app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080